module.exports = {
    type: "interactionCreate",
    allowedInteractionTypes: ["button", "selectMenu"],
    code: `
    $onlyIf[$advancedTextSplit[$customID;_;0]==musicplayer;]
    $let[cid;$getCache[musicplayer_message_$guildID_channelid]]
    $let[mid;$getCache[musicplayer_message_$guildID_messageid]]
    $onlyIf[$get[mid]==$messageID;$async[$!disableComponentsOf[$channelID;$messageID]] $!deferUpdate]
    $onlyIf[$voiceID[$guildID;$clientID]!=;]
    $let[crdjcs_0f;$callFunction[checkDJRoleUser]]
    $if[$get[crdjcs_0f]==false;
    $onlyIf[$and[$voiceID[$guildID;$clientID]!=;$voiceID[$guildID;$authorID]!=$voiceID[$guildID;$clientID]]!=true;]
    ;
    $let[crdjcr_0f;$advancedTextSplit[$get[crdjcs_0f];|;1]]
    $onlyIf[$hasRoles[$guildID;$authorID;$get[crdjcr_0f]];$ephemeral $replace[$callFunction[useCustomMusicMessage;config_errorIsSameDJVC];{role};<@&$get[crdjcr_0f]>]]
    ]
    $if[$advancedTextSplit[$customID;_;1]==nodequeue;
    $!clearInterval[intervalmusicmessage_$guildID_$get[cid]]
    $if[$selectMenuValues[0]==0;
    $!skipTrack
    ;
    $!skipTo[$selectMenuValues[0]]
    ]
    $!deferUpdate
    ]
    $if[$advancedTextSplit[$customID;_;1]==loop;
    $if[$getLoopMode==OFF;$setLoopMode[TRACK];
    $if[$getLoopMode==TRACK;$setLoopMode[QUEUE];$setLoopMode[OFF]
    ]]]
    $if[$advancedTextSplit[$customID;_;1]==shuffle;
    $let[statusshuffle;$getCache[musicplayer_message_$guildID_isshuffle]]
    $if[$get[statusshuffle];
    $!unShuffleQueue
    $setCache[musicplayer_message_$guildID_isshuffle;false]
    ;
    $!shuffleQueue
    $setCache[musicplayer_message_$guildID_isshuffle;true]
    ]]
    $if[$advancedTextSplit[$customID;_;1]==lyrics;
    $ephemeral
    $defer
    $jsonLoad[result;$callFunction[getLyricsTrack;$if[$charCount[$trackInfo[title];-]==0;$advancedTextSplit[$trackInfo[author];-;0] - $advancedTextSplit[$trackInfo[title];(;0];$advancedTextSplit[$trackInfo[title];(;0]];;false;false]]
    $onlyIf[$env[result;results]!=;$callFunction[useCustomMusicMessage;config_errorNoResultLyrics]]
    $let[loadlyrics;$inflate[$env[result;results;lyric];hex]]
    $interactionReply[
    $if[$charCount[$get[loadlyrics]]>3000;$attachment[$get[loadlyrics];lyrics-$getTimestamp.txt;true]]
    $title[$decodeURI[$env[result;results;autocomplete]];$env[result;results;url]]
    $description[$codeBlock[$cropText[$get[loadlyrics];0;3000;\n\n($callFunction[useCustomMusicMessage;config_errorOverResultLyrics])]]]
    $footer[$toTitleCase[$env[result;results;provider]];$callFunction[useIcon;$env[result;results;provider]]]
    $thumbnail[$env[result;results;thumbnail]]
    $color[$callFunction[useIcon;color_embed]]
    $timestamp
    ]
    ]
    $if[$advancedTextSplit[$customID;_;1]==lastfm;
    $ephemeral
    $interactionReply[
    $footer[Fetching;$callFunction[useIcon;loading];0]
    $color[$callFunction[useIcon;color_embed];0]
    $footer[Fetching;$callFunction[useIcon;loading];1]
    $color[$callFunction[useIcon;color_embed];1]
    ]
    $let[a;$callFunction[discoverArtistLastFm;$advancedTextSplit[$trackInfo[author];- Topic;0]]]
    $onlyIf[$get[a]!=null;$callFunction[useCustomMusicMessage;config_errorNoResultSearch]]
    $interactionReply[$get[a]]
    ]
    $if[$advancedTextSplit[$customID;_;1]==volumedown;
    $!setVolume[$if[$sub[$getVolume;10]>=0;$sub[$getVolume;10];0]]
    ]
    $if[$advancedTextSplit[$customID;_;1]==volumeup;
    $!setVolume[$if[$sum[$getVolume;10]<=150;$sum[$getVolume;10];150]]
    ]
    $if[$advancedTextSplit[$customID;_;1]==volumemute;
    $!setVolume[$if[$getVolume==0;50;0]]
    ]
    $if[$advancedTextSplit[$customID;_;1]==stopplayer;
    $!clearInterval[intervalmusicmessage_$guildID_$get[cid]]
    $!deleteCache[cachesearchistory_user_autocomplete_$authorID]
    $async[$leaveVoiceChannel]
    $!deferUpdate
    ]
    $if[$advancedTextSplit[$customID;_;1]==actionplayer;
    $if[$isPaused;$!resumeTrack;$!pauseTrack]
    ]
    $if[$advancedTextSplit[$customID;_;1]==seekdown;
    $if[$getCache[musicplayer_message_$guildID_attemptseek]==true;$ephemeral $interactionReply[It's still processing.] $stop]
    $ephemeral
    $defer
    $!clearInterval[intervalmusicmessage_$guildID_$get[cid]]
    $async[
    $let[curduration;$if[$callFunction[configMusic;interval_message];$callFunction[musicVirtualDuration;$guildID;$get[cid]];$playerElapsedTime]]
    $let[seeks;10000]
    $let[tests;$callFunction[musicVirtualDuration;$guildID;$get[cid];$sub[$get[curduration];$get[seeks]]]]
    $setCache[musicplayer_message_$guildID_attemptseek;true]
    $let[resseek;$if[$sub[$get[curduration];$get[seeks]]<0;0;$sub[$get[curduration];$get[seeks]]]]
    $!seekTrack[$get[resseek]]
    ]
    $!interactionDelete
    ]
    $if[$advancedTextSplit[$customID;_;1]==seekup;
    $if[$getCache[musicplayer_message_$guildID_attemptseek]==true;$ephemeral $interactionReply[It's still processing.] $stop]
    $ephemeral
    $defer
    $!clearInterval[intervalmusicmessage_$guildID_$get[cid]]
    $async[
    $let[curduration;$if[$callFunction[configMusic;interval_message];$callFunction[musicVirtualDuration;$guildID;$get[cid]];$playerElapsedTime]]
    $let[seeks;10000]
    $let[tests;$callFunction[musicVirtualDuration;$guildID;$get[cid];$sum[$get[curduration];$get[seeks]]]]
    $setCache[musicplayer_message_$guildID_attemptseek;true]
    $let[resseek;$if[$sum[$get[curduration];$get[seeks]]<0;0;$sum[$get[curduration];$get[seeks]]]]
    $!seekTrack[$get[resseek]]
    ]
    $!interactionDelete
    ]
    $onlyIf[$checkContains[$advancedTextSplit[$customID;_;1];stopplayer;lyrics;nodequeue;seekup;seekdown;lastfm]!=true;]
    $async[$!deferUpdate]
    $callFunction[updateCurrentMusicPlayer]
    `
}