module.exports = {
    name: "extractTrack",
    params: [{
        name: "url", // string
        description: "To provide a information",
        required: true
    },
    {
        name: "userAgent", // string
        description: "Spoof Client",
        required: false
    },
    {
        name: "limitChar", // int
        description: "Limit Character to 2000",
        required: false
    }],
    code: `
    $let[url;$env[url]]
    $let[spliturl;$advancedTextSplit[$get[url];://;1]]
    $let[agent;$if[$or[$env[userAgent]==;$env[userAgent]==null];$callFunction[configMusic;default_userAgent_desktop];$env[userAgent]]]
    $jsonLoad[filterid;$callFunction[filterMediaID;https://$get[spliturl]]]
    $onlyIf[$or[$env[filterid;id]==null;$env[filterid;type]==null]!=true;$return]
    $arrayLoad[results]
    
    $if[$env[filterid;type]==youtube;
    $let[tryattempt;0]
    $localFunction[refreshyt;
    $if[$env[retry]==true;
    $if[$get[tryattempt]>=3;$return]
    $letSum[tryattempt;1]
    ]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpSetBody[{"videoId":"$env[filterid;id]","context":{"client":{"clientName":2,"clientVersion":"2.20261231","visitorData":"$getCache[initclientmusic;authmusic_youtube_visitor]"}}}]
    $httpAddHeader[Accept-Encoding;br, gzip]
    $httpSetContentType[Text]
    $let[http;$httpRequest[https://m.youtube.com/youtubei/v1/player?prettyPrint=false&fields=responseContext(visitorData),playabilityStatus,videoDetails(videoId,title,lengthSeconds,channelId,isCrawlable,viewCount,author,isPrivate,isLiveContent);POST;reshttp]]
    $jsonLoad[reshttp;$env[reshttp]]
    $c[Fallback]
    $if[$and[$env[reshttp;playabilityStatus;status]!=OK;$env[reshttp;videoDetails;videoId]==];
    $httpAddHeader[User-Agent;$get[agent]]
    $httpAddHeader[Accept-Encoding;br, gzip]
    $httpAddHeader[Cookie;$getCache[initclientmusic;authmusic_youtube_tempcookies]]
    $httpSetContentType[Text]
    $let[http2;$httpRequest[https://www.youtube.com/watch?v=$env[filterid;id];GET]]
    $let[outputhtyt;$advancedTextSplit[$httpResult;var ytInitialData =;1;\\;;0]]
    $onlyIf[$isJSON[$get[outputhtyt]];$callLocalFunction[refreshyt;true] $return]
    $jsonLoad[reshttptest;{}]
    $jsonLoad[reshttp2;$get[outputhtyt]]
    $jsonLoad[resfindindex;$env[reshttp2;contents;twoColumnWatchNextResults;results;results;contents]]
    $!jsonSet[reshttptest;videoId;$env[reshttp2;currentVideoEndpoint;watchEndpoint;videoId]]
    $!jsonSet[reshttptest;title;$env[reshttp2;contents;twoColumnWatchNextResults;results;results;contents;$arrayFindIndex[resfindindex;g;$checkCondition[$env[g;videoPrimaryInfoRenderer]!=]];videoPrimaryInfoRenderer;title;runs;0;text]]
    $!jsonSet[reshttptest;lengthSeconds;0] $c[i couldn't find which data return that]
    $!jsonSet[reshttptest;channelId;$env[reshttp2;contents;twoColumnWatchNextResults;results;results;contents;$arrayFindIndex[resfindindex;g;$checkCondition[$env[g;videoSecondaryInfoRenderer]!=]];videoSecondaryInfoRenderer;owner;videoOwnerRenderer;navigationEndpoint;browseEndpoint;browseId]]
    $!jsonSet[reshttptest;isCrawlable;true] $c[i couldn't find which data return that]
    $!jsonSet[reshttptest;viewCount;"$advancedReplace[$advancedTextSplit[$env[reshttp2;contents;twoColumnWatchNextResults;results;results;contents;$arrayFindIndex[resfindindex;g;$checkCondition[$env[g;videoPrimaryInfoRenderer]!=]];videoPrimaryInfoRenderer;viewCount;videoViewCountRenderer;viewCount;simpleText]; ;0];,;;.;]"]
    $!jsonSet[reshttptest;author;$env[reshttp2;contents;twoColumnWatchNextResults;results;results;contents;$arrayFindIndex[resfindindex;g;$checkCondition[$env[g;videoSecondaryInfoRenderer]!=]];videoSecondaryInfoRenderer;owner;videoOwnerRenderer;title;runs;0;text]]
    $!jsonSet[reshttptest;isPrivate;$checkCondition[$arrayFindIndex[resfindindex;g;$checkCondition[$env[g;videoPrimaryInfoRenderer]!=]]==-1]]
    $!jsonSet[reshttptest;isLiveContent;$if[$env[reshttp2;contents;twoColumnWatchNextResults;results;results;contents;$arrayFindIndex[resfindindex;g;$checkCondition[$env[g;videoPrimaryInfoRenderer]!=]];videoPrimaryInfoRenderer;viewCount;videoViewCountRenderer;isLive]!=;$env[reshttp2;contents;twoColumnWatchNextResults;results;results;contents;$arrayFindIndex[resfindindex;g;$checkCondition[$env[g;videoPrimaryInfoRenderer]!=]];videoPrimaryInfoRenderer;viewCount;videoViewCountRenderer;isLive];$startsWith[$env[reshttp2;contents;twoColumnWatchNextResults;results;results;contents;$arrayFindIndex[resfindindex;g;$checkCondition[$env[g;videoPrimaryInfoRenderer]!=]];videoPrimaryInfoRenderer;dateText;simpleText];Started streaming]]]
    $let[results;{"status":null,"results":$if[$env[reshttptest;videoId]==;null;$jsonStringify[reshttptest]]}]
    ;
    $if[$env[reshttp;responseContext;visitorData]!=;$setCache[initclientmusic;authmusic_youtube_visitor;$env[reshttp;responseContext;visitorData]]]
    $let[results;{"status":null,"results":$if[$env[reshttp;videoDetails]==;null;$env[reshttp;videoDetails]]}]
    ]
    ;retry]
    $callLocalFunction[refreshyt;false]
    ]
    $if[$env[filterid;type]==soundcloud;
    $let[keturl;https://$get[spliturl]]
    $if[$charCount[$advancedTextSplit[$get[spliturl];/;0];.]>=2;$!djsEval[fetch(ctx.getKeyword("keturl"), { method: "HEAD" }).then(a => ctx.setKeyword("keturl", a.url)).catch()]]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpAddHeader[Accept-Encoding;br, gzip]
    $httpSetContentType[Text]
    $let[http;$httpRequest[https://api-v2.soundcloud.com/resolve?url=$get[keturl]&client_id=$getCache[initclientmusic;authmusic_soundcloud];GET;reshttp]]
    $let[a;$env[reshttp]]
    $let[results;{"status":null,"results":$if[$get[a]=={};null;$advancedReplace[$get[a];/preview/progressive;/preview/progressive?client_id=$getCache[initclientmusic;authmusic_soundcloud_fall];/stream/progressive;/stream/progressive?client_id=$getCache[initclientmusic;authmusic_soundcloud_fall];/preview/hls;/preview/hls?client_id=$getCache[initclientmusic;authmusic_soundcloud_fall];/stream/hls;/stream/hls?client_id=$getCache[initclientmusic;authmusic_soundcloud_fall]]]}]
    ]
    $if[$env[filterid;type]==spotify;
    $let[tryattempt;0]
    $localFunction[refreshspotify;
    $if[$env[retry]==true;
    $onlyIf[$get[tryattempt]<3;$return]
    $callFunction[generateAuthKeys;spotify;;false]
    $letSum[tryattempt;1]
    ]
    $let[mdhedroute_spotify;{
    "App-Platform": "WebPlayer",
    "Authorization": "Bearer $getCache[initclientmusic;authmusic_spotify]",
    "Sec-Fetch-Site": "none",
    "User-Agent": "$get[agent]"
    }]
    $let[mdquery;https://api.spotify.com/v1/tracks/$advancedTextSplit[$env[filterid;id];/;1]?market=US]
    $let[b;$djsEval[const { request, Agent } = require("undici")\\; request(ctx.getKeyword("mdquery"), { dispatcher: new Agent({ connect: { family: 4 } }), headers: JSON.parse(ctx.getKeyword("mdhedroute_spotify")), method: "GET" }).then(a => { ctx.setKeyword('http', a.statusCode)\\; return a.body.text() }).catch()]]
    $onlyIf[$or[$get[http]==401;$get[http]==400]!=true;$callLocalFunction[refreshspotify;true]]
    $if[$or[$get[http]==403;$get[http]==429];
    $httpAddHeader[Accept-Encoding;br, gzip]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpSetContentType[Text]
    $let[http;$httpRequest[https://open.spotify.com/embed/$env[filterid;id]?utm_source=oembed;GET;a]]
    $if[$get[http]==403;
    $let[a;null]
    ;
    $let[a;$advancedTextSplit[$env[a];type="application/json">;1;</script>;0]]
    ]
    ;
    $let[a;$get[b]]
    ]
    $let[results;{"status":null,"results":$if[$get[a]==;null;$get[a]]}]
    ;retry]
    $callLocalFunction[refreshspotify;false]
    ]
    $if[$env[filterid;type]==applemusic;
    $httpAddHeader[Accept-Encoding;br, gzip]
    $httpAddHeader[Accept-Language;en]
    $httpAddHeader[Accept;*/*]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpSetContentType[Text]
    $let[http;$httpRequest[https://itunes.apple.com/lookup?id=$env[filterid;id];GET;a]]
    $jsonLoad[a;$env[a]]
    $let[results;{"status":null,"results":$if[$env[a;results;0]==;null;$env[a;results;0]]}]
    ]
    $if[$env[filterid;type]==tiktokmob;
    $let[testtempjr;$djsEval[fetch("$replace[$get[url];vm.tiktok.com;vt.tiktok.com]", { method: "HEAD" }).then(a => a.url).catch()]]
    $jsonLoad[filterid;$callFunction[filterMediaID;$get[testtempjr]]]
    $onlyIf[$or[$env[filterid;id]==;$env[filterid;id]==null]!=true;$return]
    ]
    $if[$env[filterid;type]==tiktok;
    $let[ttcounting;0]
    $localFunction[fetchttdl;
    $if[$get[ttcounting]>=5;$return]
    $if[$env[retry]==true;$letSum[ttcounting;1]]
    $httpAddHeader[Accept-Encoding;br, gzip]
    $httpAddHeader[Accept-Language;en]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpAddHeader[Cookie;$inflate[$getCache[initclientmusic;authmusic_tiktok];base64]]
    $httpSetContentType[Text]
    $let[http;$httpRequest[https://m.tiktok.com/v/$env[filterid;id];GET]]
    $jsonLoad[a;$advancedTextSplit[$httpResult;"webapp.video-detail":;1;,"webapp;0]]
    $if[$isJSON[$env[a]]==false;$callLocalFunction[fetchttdl;true] $return]
    ;retry]
    $callLocalFunction[fetchttdl;false]
    $if[$env[a;statusCode]!=0;$return[{"status":null,"results":{"error":"$env[a;statusMsg]"}}]]
    $jsonLoad[b;$default[$env[a;itemInfo;itemStruct];{}]]
    $if[$env[b;author]==;
    $httpAddHeader[Accept-Encoding;br, gzip]
    $httpAddHeader[Accept-Language;en]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpAddHeader[Cookie;$inflate[$getCache[initclientmusic;authmusic_tiktok];base64]]
    $httpSetContentType[Text]
    $let[http;$httpRequest[https://www.tiktok.com/player/api/v1/items?item_ids=$env[filterid;id];GET]]
    $if[$or[$get[http]==200;$isJSON[$httpResult]]==false;$return[{"status":null,"results":{"error":"IP blocked"}}]]
    $jsonLoad[a;$httpResult]
    $onlyIf[$env[a;items;0]!=;$return[{"status":null,"results":{"error":"Content unavailable"}}]]
    $jsonLoad[b;$env[a;items;0]]
    ]
    $let[results;{"status":null,"results":$if[$env[b]==;null;$jsonStringify[b]]}]
    ]
    $if[$env[filterid;type]==tiktokmusic;
    $let[tryattempt;0]
    $localFunction[refreshvm;
    $if[$env[retry]==true;
    $onlyIf[$get[tryattempt]<10;$return]
    $letSum[tryattempt;1]
    ]
    $httpSetContentType[Text]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpAddHeader[Accept;application/json]
    $httpAddHeader[Accept-Encoding;br, gzip]
    $httpAddHeader[Accept-Language;en]
    $httpAddHeader[Cookie;$inflate[$getCache[initclientmusic;authmusic_tiktok];base64]]
    $httpAddHeader[X-Khronos;$round[$divide[$getTimestamp;1000]]]
    $httpAddHeader[X-Argus;]
    $c[Doesn't require to solve challenge for this, for now]
    $!httpRequest[https://api-boot.tiktokv.com/aweme/v1/music/aweme/?music_id=$env[filterid;id]&aid=1233&device_id=$randomNumber[100000000;999999999;false]$randomNumber[1000000000;9999999999;false]&user_is_login=true&cookie_enabled=true&region=&referer=;GET;a]
    $onlyIf[$env[a]!=;$callLocalFunction[refreshvm;true]]
    $jsonLoad[a;$env[a]]
    $jsonLoad[a;$env[a;aweme_list]]
    $let[index;$arrayFindIndex[a;b;$checkCondition[$env[b;added_sound_music_info;mid]==$env[filterid;id]]]]
    $if[$get[index]==-1;
    $httpAddHeader[Accept-Encoding;br, gzip]
    $httpAddHeader[Accept-Language;en]
    $httpAddHeader[Accept;*/*]
    $httpAddHeader[User-Agent;Mozilla/5.0 (compatible\\; Discordbot/2.0\\; +https://discordapp.com)]
    $httpSetContentType[Text]
    $onlyIf[$httpRequest[https://www.tiktok.com/music/-$env[filterid;id];GET]==200;$callLocalFunction[refreshvm;true]]
    $if[$checkContains[$advancedTextSplit[$httpResult;property="al:android:url";1;content=";1;";0];//music/detail/];
    $let[cl;$djsEval[require("entities").decodeHTML("$advancedTextSplit[$httpResult;<title>;1;</title>;0]")]]
    $let[stctitle;$toLowercase[$advancedTextSplit[$replace[$get[cl];♬ ;]; | ;0; & ;0] $advancedTextSplit[$replace[$get[cl];♬ ;]; | ;1]]]
    ;
    $return
    ]
    $httpAddHeader[Accept-Encoding;br, gzip]
    $httpAddHeader[Accept-Language;en]
    $httpAddHeader[Accept;*/*]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpAddHeader[Cookie;$inflate[$getCache[initclientmusic;authmusic_tiktok];base64]]
    $let[xgnarly;$callFunction[xGnarlyTiktok;count=10&cursor=0&aid=1180&device_id=$getCache[initclientmusic;authmusic_tiktok_did]&user_is_login=true&cookie_enabled=true&region=&referer=&keyword=$encodeURI[$get[stctitle]];$get[agent]]]
    $!httpRequest[https://api-boot.tiktokv.com/aweme/v1/music/search/?count=10&cursor=0&aid=1180&device_id=$getCache[initclientmusic;authmusic_tiktok_did]&user_is_login=true&cookie_enabled=true&region=&referer=&keyword=$encodeURI[$get[stctitle]]&X-Gnarly=$get[xgnarly];GET;c]
    $onlyIf[$env[c]!=;$return]
    $jsonLoad[c;$env[c]]
    $jsonLoad[c;$env[c;music_info_list]]
    $jsonLoad[c;$env[c;$arrayFindIndex[c;k;$checkCondition[$env[k;music;id_str]==$env[filterid;id]]]]]
    $let[results;{"status":null,"results":$if[$env[c]==;null;$env[c;music]]}]
    ;
    $let[results;{"status":null,"results":$if[$env[a;$get[index]]==;null;$env[a;$get[index];music]]}]
    ]
    ;retry]
    $callLocalFunction[refreshvm;false]
    ]
    $if[$env[filterid;type]==facebook;
    $let[url;https://web.facebook.com$advancedTextSplit[$get[url];facebook.com;1]]
    $!djsEval[fetch(ctx.getKeyword("url"), {method: "HEAD" }).then(a => ctx.setKeyword("url", a.url)).catch()]
    $httpAddHeader[Accept;text/html]
    $httpAddHeader[Accept-Language;en]
    $httpAddHeader[Accept-Encoding;br, gzip]
    $httpAddHeader[Sec-Fetch-Dest;iframe]
    $httpAddHeader[Sec-Fetch-Site;none]
    $httpSetContentType[Text]
    $!httpRequest[https://web.facebook.com/plugins/video.php?href=$get[url]&show_text=true;GET]
    $let[cs;$default[$advancedTextSplit[$httpResult;"videoData":\\[;1;,"player_version;0];{]]
    $jsonLoad[b;$get[cs]}]
    $if[$env[b;video_id]!=;
    $let[flrt;$advancedTextSplit[$httpResult;class="text_exposed_root"><p>;1;<;0]]
    $if[$get[flrt]==;
    $arrayLoad[kjvj;class=";$httpResult]
    $let[isd;$env[kjvj;$arrayFindIndex[kjvj;kjvjp;$checkCondition[$advancedTextSplit[$env[kjvjp];userContent;1;";1]!=]]]]
    $let[flrt;$trim[$advancedTextSplit[$get[isd];<p>;1;<;0]]]
    $arrayLoad[kjvj]
    ]
    $!jsonSet[b;text;$get[flrt]]
    $!jsonSet[b;owner;$advancedTextSplit[$httpResult;<a title=";1;" target=;0]]
    ]
    $let[results;{"status":null,"results":$jsonStringify[b]}]
    ]
    $if[$env[filterid;type]==instagram;
    $httpAddHeader[Accept;text/html, */*]
    $httpAddHeader[Accept-Language;en]
    $httpAddHeader[Accept-Encoding;br, gzip]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpAddHeader[Sec-Fetch-Site;none]
    $httpAddHeader[Sec-Fetch-Dest;document]
    $httpSetContentType[Text]
    $let[uynsd;$httpRequest[https://www.instagram.com/$env[filterid;id];GET]]
    $if[$get[uynsd]!=200;
    $httpAddHeader[Accept;text/html, */*]
    $httpAddHeader[Accept-Language;en]
    $httpAddHeader[Sec-Fetch-Dest;iframe]
    $httpAddHeader[Sec-Fetch-Site;none]
    $httpAddHeader[Accept-Encoding;br, gzip]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpAddHeader[Referer;https://www.instagram.com/]
    $httpSetContentType[Text]
    $let[uynsdf;$httpRequest[https://www.instagram.com/p/$advancedTextSplit[$env[filterid;id];/;$charCount[$env[filterid;id];/]]/embed?_fb_noscript=1;GET]]
    $onlyIf[$or[$get[uynsdf]==403;$get[uynsdf]==429]!=true;$return[{"status":null,"results":{"error":"Sign in for view this content"}}]]
    $let[temdata;$advancedTextSplit[$httpResult;"contextJSON":";1;"}\\]\\];0]]
    $jsonLoad[kvo;$replace[$get[temdata];\\\\\;]]
    $jsonLoad[lck;$env[kvo;gql_data]]
    ;
    $arrayLoad[iru;script type="application/json";$httpResult]
    $jsonLoad[irk;$default[$advancedTextSplit[$env[iru;$arrayFindIndex[iru;r;$checkCondition[$advancedTextSplit[$env[r];"RelayPrefetchedStreamCache";1;"xig_polaris_media";1]!=]]];data-sjs>;1;</script>;0];{}]]
    $jsonLoad[lcpr;$default[$env[irk;require;0;3;0;__bbox;require];{}]]
    $let[findbboxindex;$arrayFindIndex[lcpr;ot;$checkCondition[$env[ot;3;1;__bbox;result;data;xig_polaris_media]!=]]]
    $jsonLoad[lck;$default[$env[irk;require;0;3;0;__bbox;require;$get[findbboxindex];3;1;__bbox;result;data;xig_polaris_media;if_not_gated_logged_out];{}]]
    $onlyIf[$env[lck;pk]!=;$return[{"status":null,"results":{"error":"Not a video or you don't have permission to view it"}}]]
    ]
    $let[results;{"status":null,"results":$jsonStringify[lck]}]
    ]
    $if[$env[filterid;type]==instagramaudio;
    $httpSetBody[audio_cluster_id=$env[filterid;id]&max_id&original_sound_audio_asset_id=$env[filterid;id]]
    $httpAddHeader[Content-Type;application/x-www-form-urlencoded]
    $httpAddHeader[User-Agent;Instagram 414.0.0 Android]
    $httpAddHeader[Sec-Fetch-Site;same-origin]
    $httpAddHeader[Origin;https://i.instagram.com]
    $httpAddHeader[Accept-Language;en]
    $httpAddHeader[Accept-Encoding;br, gzip]
    $httpSetContentType[Text]
    $!httpRequest[https://i.instagram.com/api/v1/clips/music/;POST]
    $onlyIf[$isJSON[$httpResult];$return]
    $jsonLoad[lkig;$httpResult]
    $let[results;{"status":null,"results":$if[$env[lkig;items;0]==;null;$jsonStringify[lkig]]}]
    ]
    $if[$env[filterid;type]==bandcamp;
    $httpSetContentType[Text]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpAddHeader[Accept-Encoding;br, gzip]
    $httpAddHeader[Accept-Language;en]
    $!httpRequest[$env[filterid;id];GET]
    $let[a;$advancedTextSplit[$httpResult;data-tralbum=";1;";0]]
    $let[a;$djsEval[require("entities").decodeHTML(ctx.getKeyword("a"))]]
    $jsonLoad[a;$default[$get[a];{}]]
    $if[$env[a;trackinfo;0;artist]==null;
    $let[b;$advancedTextSplit[$httpResult;data-band=";1;";0]]
    $let[b;$djsEval[require("entities").decodeHTML(ctx.getKeyword("b"))]]
    $jsonLoad[b;$default[$get[b];{}]]
    $!jsonSet[a;trackinfo;0;artist;$env[b;name]]
    ]
    $let[results;{"status":null,"results":$if[$env[a;trackinfo]==;null;$env[a;trackinfo;0]]}]
    ]
    $if[$env[filterid;type]==twitter;
    $httpAddHeader[Accept-Encoding;br, gzip]
    $httpAddHeader[Accept-Language;en]
    $httpAddHeader[Accept;*/*]
    $httpAddHeader[Sec-Fetch-Dest;iframe]
    $httpAddHeader[Sec-Fetch-Site;none]
    $httpAddHeader[User-Agent;$get[agent]]
    $!httpRequest[https://cdn.syndication.twimg.com/tweet-result?id=$env[filterid;id]&lang=en&token=abc;GET]
    $jsonLoad[thers;$httpResult]
    $let[results;{"status":null,"results":$if[$env[thers]==;null;$jsonStringify[thers]]}]
    ]
    $if[$env[filterid;type]==threads;
    $httpAddHeader[Accept;text/html, */*]
    $httpAddHeader[Accept-Language;en]
    $httpAddHeader[Accept-Encoding;br, gzip]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpAddHeader[Sec-Fetch-Dest;iframe]
    $httpAddHeader[Sec-Fetch-Site;none]
    $httpAddHeader[Referer;https://www.threads.com/]
    $httpSetContentType[Text]
    $let[uynsd;$httpRequest[https://www.threads.com/@/post/$env[filterid;id]/embed?_fb_noscript=1;GET]]
    $onlyIf[$or[$get[uynsd]==403;$get[uynsd]==429]!=true;$return[{"status":null,"results":{"error":"Sign in for view this content"}}]]
    $let[vra1;$default[$advancedTextSplit[$httpResult;class="HeaderLink"><span>;1;</span>;0];null]]
    $let[vra2;$default[$advancedTextSplit[$httpResult;class="BodyTextContainer"><span>;1;</span>;0];null]]
    $let[vra3;$default[$advancedTextSplit[$httpResult;source src=";1;";0];]]
    $let[vra1;$djsEval[require("entities").decodeHTML(ctx.getKeyword("vra1"))]]
    $let[vra2;$djsEval[require("entities").decodeHTML(ctx.getKeyword("vra2"))]]
    $let[vra3;$djsEval[require("entities").decodeHTML(ctx.getKeyword("vra3"))]]
    $jsonLoad[rty;{}]
    $!jsonSet[rty;author;$get[vra1]]
    $!jsonSet[rty;title;$get[vra2]]
    $!jsonSet[rty;media;$get[vra3]]
    $let[results;{"status":null,"results":$jsonStringify[rty]}]
    ]

    $let[resultforeturn;$get[results]]
    $return[$if[$and[$env[limitChar]==true;$env[limitChar]!=false];$cropText[$get[resultforeturn];0;2000;];$get[resultforeturn]]]
    `
}